examples/next/pages/_app.tsx
examples/next/pages/index.tsx
packages/next-international/README.md
packages/next-international/package.json
packages/next-international/src/i18n/create-i18n-provider.tsx

Add a new `fallback` option (that is optional) to `I18nProvider`, for when you don't want to have the initial locale SSRed.

feat: add fallback to I18nProvider for client-side loading

---

packages/next-international/src/helpers/log.ts
packages/next-international/src/i18n/create-get-locale-static-props.ts
packages/next-international/src/i18n/create-i18n-provider.tsx

Add an `error` log function for `i18n.defaultLocale` & `i18n.locales` not being defined.

feat: improve error messages

---

examples/next/locales/en.ts
examples/next/locales/fr.ts
examples/next/pages/index.tsx
packages/next-international/README.md
packages/next-international/package.json
packages/next-international/src/i18n/create-use-i18n.ts
packages/next-international/src/types.ts

Add `scopedT` to avoid duplicating the same scopes over and over, with type safety.
```ts
const t = scopedT('pages.settings')
t('title')
t('description', { identifier })
t('ct')
```

feat: add scopes

---

examples/next/locales/en.ts
examples/next/locales/fr.ts
examples/next/pages/_app.tsx
examples/next/pages/index.tsx
packages/next-international/README.md
packages/next-international/__tests__/fallback-locale.test.tsx
packages/next-international/__tests__/utils/en.ts
packages/next-international/src/i18n/create-i18n-provider.tsx
packages/next-international/src/i18n/create-use-i18n.ts
packages/next-international/src/types.ts

Add `fallbackLocale` option to `I18nProvider` to fallback to the given locale when a translation is not found for a given key.

feat: add fallback locale

---

package.json
packages/international-types/__tests/keys.test.ts
packages/international-types/__tests/params.test.ts
packages/international-types/__tests/scopes.test.ts
packages/international-types/index.ts
pnpm-lock.yaml
vitest.config.ts

Add tests for utility types of `international-types` using `vite-plugin-vitest-typescript-assert` within Vitest.

test(international-types): add type tests

---

packages/next-international/package.json

Without this I wasn't able to install the library in an `npm` project. `pnpm` seems to be fine with the syntax either way.
The error I had before this fix
```
npm ERR! Found: next@12.2.4
npm ERR! node_modules/next
npm ERR!   next@"12.2.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"12.x | 11.x" from next-international@0.1.1
npm ERR! node_modules/next-international
npm ERR!   next-international@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

fix: correct syntax for peer deps

---

examples/next/locales/index.ts
examples/next/pages/ssr.tsx
packages/next-international/README.md
packages/next-international/__tests__/create-i18n.test.ts
packages/next-international/__tests__/get-locale-props.test.ts
packages/next-international/src/i18n/create-get-locale-static-props.ts
packages/next-international/src/i18n/create-i18n.ts

Closes #23 
This PR renames `getLocaleStaticProps` to `getLocaleProps` and makes it possible to use with both `getStaticProps` or `getServerSideProps`.
To not introduce a breaking change, the existing `getLocaleStaticProps` still exists and forward to `getLocaleProps`

feat: allow SSR and SSG with getLocaleProps

---

packages/next-international/__tests__/use-i18n.test.tsx
packages/next-international/__tests__/utils/en.ts
packages/next-international/src/i18n/create-use-i18n.ts
tsconfig.json

Right now it`s not possible to use a translation text that uses the same variable more than once, because only the first instance will be interpolated

feat(next-international): use a regex to allow multiple interpolations

---

examples/next/pages/index.tsx
examples/next/pages/ssr.tsx
packages/next-international/README.md
packages/next-international/__tests__/use-i18n.test.tsx
packages/next-international/src/i18n/create-use-i18n.ts
packages/next-international/src/index.tsx
packages/next-international/src/types.ts

We are through the process of adding internationalization to our application and found the existing functions (`t` and `scopedT`) to be limiting as they only allowed parameters to be strings.
This pull request implements `rt` and `scopedRT` which allow parameters to be react components like `<strong>John</strong>`
This was just quickly put together, so I'm open to changing anything!
I didn't know where to put the type `ReactParamsObject` (as `international-types` doesn't depend on React, and shouldn't - as it is more generic that way) so I put it in `create-use-i18n` - help appreciated is on where it should actually be!

feat: implement react translation functions

---

examples/next/package.json
packages/international-types/__tests/params.test.ts
packages/international-types/index.ts
packages/international-types/package.json
packages/next-international/package.json
pnpm-lock.yaml

Support plural forms (e.g `{value, plural, =1 {...} other {...}}`, param should be `value`) without breaking current params extraction.

feat(international-types): support plural forms

---

examples/next/next.config.js
examples/next/pages/index.tsx
packages/next-international/src/i18n/create-i18n-provider.tsx

When using `getLocaleProps` with `getStaticProps` / `getServerSideProps`, the locale was still loading client-side.

fix(next-international): don't load locale client-side if SSR/SSGed

---

packages/international-types/__tests/params.test.ts
packages/international-types/index.ts
packages/international-types/package.json

Improve the params extraction to better support plural with `=0`, `=1`, `other` delimiters

feat(international-types): improve plural extraction

---

examples/next/locales/index.ts
examples/next/pages/index.tsx
examples/next/pages/ssr.tsx
packages/next-international/__tests__/fallback-locale.test.tsx
packages/next-international/__tests__/i18n-provider.test.tsx
packages/next-international/__tests__/use-change-locale.test.tsx
packages/next-international/__tests__/use-i18n.test.tsx
packages/next-international/__tests__/use-scoped-i18n.test.tsx
packages/next-international/src/i18n/create-i18n.ts
packages/next-international/src/i18n/create-t.ts
packages/next-international/src/i18n/create-use-i18n.ts
packages/next-international/src/i18n/create-use-scoped-i18n.ts

This PR implements the first suggestion of #27:
> 1. `useI18n` only returns a non-scoped `t` function, we introduce a new `useScopedI18n` hook that takes the scope in parameters, similar to the current `scopedT`:
> 
> ```ts
> const t = useI18n() // non-scoped t
> const t = useScopedI18n("scope") // scoped t
> ```

feat: add use scoped i18n hook

---

packages/next-international/src/app/server/create-get-current-locale.ts
packages/next-international/src/app/server/index.ts

Return a correctly typed union of the locales when using `getCurrentLocale` in Server Components (similar to the current behavior with `useCurrentLocale` in pages router and client components of the app router)

fix(app-router): typesafe `getCurrentLocale` in Server Components

---

examples/next-pages/locales/en.ts
packages/international-types/index.ts
packages/next-international/README.md
packages/next-international/src/pages/create-i18n-provider.tsx
packages/next-international/src/pages/index.ts

Closes #19 
The current syntax for writing locale is:
```ts
export default {
hello: 'Hello',
welcome: 'Hello {name}!',
'about.you': 'Hello {name}! You have {age} yo',
'scope.test': 'A scope',
'scope.more.test': 'A scope',
'scope.more.param': 'A scope with {param}',
'scope.more.and.more.test': 'A scope',
'missing.translation.in.fr': 'This should work',
} as const
```
And you're now able to write locales using nested objects:
```ts
export default {
hello: 'Hello',
welcome: 'Hello {name}!',
about: {
you: 'Hello {name}! You have {age} yo',
},
scope: {
test: 'A scope',
more: {
test: 'A scope',
param: 'A scope with {param}',
and: {
more: {
test: 'A scope',
},
},
},
},
missing: {
translation: {
in: {
fr: 'This should work',
},
},
},
} as const
```

feat: nested object scopes

---

packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/server/create-get-i18n.ts
packages/next-international/src/app/server/create-get-scoped-i18n.ts
packages/next-international/src/common/flatten-locale.ts
packages/next-international/src/pages/create-i18n-provider.tsx

Closes https://github.com/QuiiBz/next-international/issues/67
`flatten` was implemented for the Pages Router, but not for the App Router.

fix(next-international): nested objects locales in App Router

---

packages/next-international/README.md

This fixes two issues in the documentation.
1. specifying the `hello` key with a string value and then also specifying it again with an object value leads to errors (at least in TS) and should not be in the example.
```An object literal cannot have multiple properties with the same name.```
2. The direct link to `Change and get the current locale` didn't work as the heading and link mismatched. I removed the article to match the links up top.

chore: fix docs

---

packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/pages/create-i18n-provider.tsx

Resolves https://github.com/QuiiBz/next-international/issues/67#issuecomment-1644039802
The fallback locale should also be flattened, or it won't resolve properly.

fix(next-international): nested objects locales with fallbackLocale

---

packages/international-types/index.ts
packages/next-international/README.md
packages/next-international/src/common/create-t.ts

Relates to #44
Following #75 
Enable type safety on the `count` params of plural translations.

feat: typesafe plural `count`

---

packages/international-types/index.ts
packages/next-international/README.md

Fix the allowed `count` values for plural tags to match the spec:
- `zero` allows 0
- `one` autocompletes 1, 21, 31, 41... but allows any number
- `two` autocompletes 2, 22, 32, 42... but allows any number
- `few`, `many` and `other` allow any number
See https://cldr.unicode.org/index/cldr-spec/plural-rules, https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html

fix(international-types): plural tags

---

packages/next-international/README.md
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/client/create-use-current-locale.ts
packages/next-international/src/app/middleware/index.ts
packages/next-international/src/app/server/get-locale-cache.tsx
packages/next-international/src/common/constants.ts
packages/next-international/src/types.ts

Closes #62 
This PR includes a few key updates.
`useParams` is a more reliable way to access the locale than `usePathname`. For example, calling `useParams` in `app/[locale]/products/[category]/[subCategory]/page.tsx` with the URL `/en/products/cars/trucks` returns `{ locale: 'en', category: 'cars', subCategory: 'trucks' }`.
When enabling the opt-in rewrite strategy, the request URLs not prefixed with the locale (e.g. `/products/cars/trucks`) are now supported. In this situation, using `usePathname` would return a URL without the locale (e.g. `/products/car/trucks`) while `useParams` still returns an object that contains the locale as the layout segment.
A config object is introduced with the `segmentName` option to allow users to change the segment name (default is `locale`) in case …

feat(next-international): `useParams` & `rewrite` strategy to hide locale from URL

---

examples/next-app/app/[locale]/client/page.tsx
examples/next-app/app/[locale]/page.tsx
examples/next-app/locales/en.ts
examples/next-app/locales/fr.ts
examples/next-pages/locales/en.ts
examples/next-pages/locales/fr.ts
examples/next-pages/pages/index.tsx
examples/next-pages/pages/ssr-ssg.tsx
packages/international-types/index.ts

Closes #87
When using `getScopedI18n` / `useScopedI18n`, we did not resolve the plural params by joining the Scope + Key and instead only used the Key to index the translation value.

fix(international-types): plurals params with scope

---

examples/next-app/app/[locale]/client/page.tsx
examples/next-app/app/[locale]/switch.tsx
examples/next-app/next.config.js
packages/next-international/README.md
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/client/create-use-change-locale.ts
packages/next-international/src/app/client/create-use-current-locale.ts
packages/next-international/src/types.ts

fix(next-international): `useChangeLocale` with `basePath`

---

packages/next-international/package.json
packages/next-international/src/app/client/create-use-change-locale.ts

fix(next-international): preserve search params with `useChangeLocale` in App Router

---

examples/next-app/middleware.ts
packages/next-international/README.md

Relates to https://github.com/QuiiBz/next-international/issues/97, update the default middleware regex to not run on /api, /_next/static, /_next/image & /favicon.ico

chore: update middleware regex

---

packages/next-international/src/app/middleware/index.ts

Relates to #99
If the resolved locale isn't configured, we fallback to the specified default locale.

fix(next-international): use default locale when Accept-Language is unknown

---

packages/next-international/README.md
packages/next-international/src/app/middleware/index.ts
packages/next-international/src/types.ts

Closes #110
Relates to #96
Relates to #108
If needed, you can override the resolution of a locale from a `Request`, which by default will try to extract it from the `Accept-Language` header. This can be useful to force the use of a specific locale regardless of the `Accept-Language` header. Note that this function will only be called if the user doesn't already have a `Next-Locale` cookie.
Navigate to the `middleware.ts` file and implement a new `resolveLocaleFromRequest` function:
```ts
// middleware.ts
const I18nMiddleware = createI18nMiddleware(['en', 'fr'] as const, 'fr', {
resolveLocaleFromRequest: request => {
// Do your logic here to resolve the locale
return 'fr'
}
})
```

feat(next-international): override locale resolution

---

packages/next-international/src/app/middleware/index.ts

Relates to #109
Fix an error when navigating to pathnames that start with a locale (e.g `en` locale with a path `/enna` would error instead of redirecting to `/en/enna`)

fix(next-international): pathname starting with locale error

---

examples/next-app/middleware.ts
packages/next-international/README.md

Closes #118
Also ignore `favicon.ico` and `robots.txt`

fix(next-international): update middleware matcher to work with images

---

packages/next-international/src/app/client/create-use-current-locale.ts

Relates to #122
Remove the return type of `createUseCurrentLocale` to keep it inferred and allow passing a config to `useCurrentLocale`.

fix(next-international): type of `useCurrentLocale`

---

packages/next-international/src/app/client/create-use-current-locale.ts
packages/next-international/src/app/server/create-get-static-params.ts
packages/next-international/src/common/constants.ts
packages/next-international/src/types.ts

Relates to https://github.com/QuiiBz/next-international/issues/122#issuecomment-1684208680

feat(next-international): allow configuring segment name in `getStaticParams`

---

examples/next-app/app/[locale]/client/page.tsx
examples/next-app/app/[locale]/switch.tsx
examples/next-app/locales/client.ts
examples/next-app/locales/server.ts
packages/next-international/README.md
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/client/create-use-change-locale.ts
packages/next-international/src/app/client/create-use-current-locale.ts
packages/next-international/src/app/client/index.ts
packages/next-international/src/app/server/create-get-static-params.ts
packages/next-international/src/app/server/index.ts
packages/next-international/src/types.ts

⚠️ BREAKING
Improve the API for configuring the App Router behaviors by moving all configurations from specific functions to `createI18n*` functions. This avoids duplicating multiple times the same configuration, and will allow for more configuration options in the future.
These changes are only affecting you if you were using these options.
Before:
```ts
// locales/client.ts
const { useChangeLocale } = createI18nClient({
en: () => import('./en'),
fr: () => import('./fr')
})
// In a Client Component
const changeLocale = useChangeLocale({
basePath: '/base'
})
```
After:
```ts
// locales/client.ts
const { useChangeLocale } = createI18nClient({
en: () => import('./en'),
fr: () => import('./fr')
}, {
basePath: '/base'
})
// In a Client Component
const changeLocale = useChangeLocale()
``` …

feat(next-international): improve config API

---

packages/next-international/src/app/middleware/index.ts

Relates to #136
When `urlMappingStrategy` is set to `rewrite`, we should redirect to the same URL without the locale when changing locale.

feat(next-international): remove locale for `useChangeLocale` with rewrite strate

---

packages/next-international/src/app/client/create-use-change-locale.ts

Relates to #138
The [Router Cache](https://nextjs.org/docs/app/building-your-application/caching#router-cache) of Next.js caches by route segments and causes issues when changing locale and navigating to already-viewed pages. Turns out we can simply call `router.refresh()` to invalidate the Router Cache and get the correct data for every page: https://nextjs.org/docs/app/building-your-application/caching#invalidation-1

fix(next-international): `changeLocale` with subsequent navigations

---

docs/pages/docs/app-setup.mdx
examples/next-app/app/[locale]/client/layout.tsx
examples/next-app/locales/server.ts
examples/next-pages/pages/_app.tsx
packages/next-international/__tests__/fallback-locale.test.tsx
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/server/create-get-i18n.ts
packages/next-international/src/app/server/create-get-scoped-i18n.ts
packages/next-international/src/app/server/create-get-static-params.ts
packages/next-international/src/app/server/index.ts
packages/next-international/src/pages/create-i18n-provider.tsx
packages/next-international/src/pages/index.ts
packages/next-international/src/types.ts

Relates to #141
⚠️ BREAKING
Improve the Fallback Locale API for both the Pages and App Router:
<details>
<summary>See changes for <code>fallbackLocale</code> prop</summary>
Before:
```tsx
// pages/_app.tsx
import en from '../locales/en'
export default function App({ Component, pageProps }: AppProps) {
return (
<I18nProvider locale={pageProps.locale} fallbackLocale={en}>
<Component {...pageProps} />
</I18nProvider>
)
}
```
After:
```tsx
// pages/_app.tsx
export default function App({ Component, pageProps }: AppProps) {
return (
<I18nProvider locale={pageProps.locale} fallbackLocale="en">
<Component {...pageProps} />
</I18nProvider>
)
}
```
</details>
<details>
<summary>See changes for <code>fallbackLocale</code> and <code>locale</code> props (in Client Components)</summary>
Before:
```tsx …
```

feat(next-international): improve fallback locale API

---

packages/next-international/src/app/client/create-use-current-locale.ts
packages/next-international/src/app/server/get-locale-cache.tsx

Relates to #144
When a locale can't be found, we now use [`notFound()`](https://nextjs.org/docs/app/api-reference/functions/not-found) instead of throwing an un-catchable error. This allows to render a [`not-found.ts`](https://nextjs.org/docs/app/api-reference/file-conventions/not-found) file easily.

feat(next-international): use `notFound()` instead of throwing un-catchable error

---

packages/next-international/src/common/create-t.ts

Relates to https://github.com/QuiiBz/next-international/issues/147
`t()` should always return a `string`, unless a parameter is a `ReactElement` where we return an array of `ReactElement`

fix(next-international): non-string params translations return string

---

docs/pages/docs/app-setup.mdx
docs/pages/docs/pages-setup.mdx
examples/next-app/app/[locale]/client/layout.tsx
examples/next-app/locales/server.ts
examples/next-pages/pages/_app.tsx
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/server/create-get-i18n.ts
packages/next-international/src/app/server/create-get-scoped-i18n.ts
packages/next-international/src/app/server/create-get-static-params.ts
packages/next-international/src/app/server/index.ts
packages/next-international/src/pages/create-i18n-provider.tsx
packages/next-international/src/pages/index.ts
packages/next-international/src/types.ts

Relates to #149
Partial revert of https://github.com/QuiiBz/next-international/pull/142 to immediately get access to the fallback locale, which is either way always loaded on the client. This provides a better UX.

refactor(next-international): load fallback locale immediately

---

packages/next-international/src/pages/create-get-locale-props.ts

fix(next-international): flatten locale in `getLocaleProps`

---

docs/pages/docs/index.mdx

I thought it would be useful for people to also know you can install this library without any problems using bun, Vercel also supports bun installation now, so I think its handy to also have it as an option.

chore(docs): add bun installation support

---

packages/next-international/src/app/middleware/index.ts

This fixes the case where strategy is rewriteDefault and locale is not defaultLocale. Everything was working, but there was an accidental logs warning.

fix(next-international): remove unintended log in middleware

---

docs/pages/docs/app-setup.mdx

Added `"client only"` at the top of the `locales/client.ts` to prevent Next.js from yelling `'client-only' cannot be imported from a Server Component module. It should only be used from a Client Component.`

chore(docs): add `'use client'` annotation

---

docs/pages/docs/app-plurals.md
docs/pages/docs/pages-plurals.md
packages/next-international/__tests__/use-i18n.test.tsx
packages/next-international/__tests__/utils/en.ts
packages/next-international/src/common/create-t.ts

Closes https://github.com/QuiiBz/next-international/issues/199

feat(next-international): plurals with count 0 works with `#zero`

---

packages/next-international/src/index.ts

Closes #229
Export `createT` and `flattenLocale`. It's not documented as it's a very niche use-case.

feat(next-international): export internal functions

---

packages/international-types/index.ts

Closes https://github.com/QuiiBz/next-international/issues/197
`FlattenLocale` should work when a locale is using both dot & object notation:
| Before | After |
|--------|--------|
| <img width="453" alt="Screenshot 2023-10-10 at 09 35 05" src="https://github.com/QuiiBz/next-international/assets/43268759/c7771c66-d0c1-4ee1-be27-d3cbe4ec315c">l | <img width="617" alt="Screenshot 2023-10-10 at 09 35 28" src="https://github.com/QuiiBz/next-international/assets/43268759/51e291b3-26b9-498f-9c08-ccf24d627ce6"> |

fix(international-types): flatten works with dot & object notation

---

.github/workflows/sherif.yml
docs/package.json
examples/next-app/package.json
examples/next-pages/package.json
packages/next-international/package.json
pnpm-lock.yaml

```
TypeError: rule.test?.test is not a function
at /Users/tom/dev/next-international/docs/next.config.js:7:72
at Array.find (<anonymous>)
at Object.webpack (/Users/tom/dev/next-international/docs/next.config.js:7:48)
at Object.webpack (/Users/tom/dev/next-international/node_modules/.pnpm/nextra@2.13.2_next@13.5.4_react-dom@18.2.0_react@18.2.0/node_modules/nextra/dist/index.js:518:65)
at getBaseWebpackConfig (/Users/tom/dev/next-international/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack-config.js:1972:32)
at async Promise.all (index 0)
at async Span.traceAsyncFn (/Users/tom/dev/next-international/node_modules/.pnpm/next@13.5.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:105:20 …
```

chore: bump next & nextra

---

packages/next-international/src/app/middleware/index.ts
packages/next-international/src/common/create-t.ts

A optional parameter of `String.prototype.split` can be used to interrupt parsing the string after the first match.
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#syntax)

perf(next-international): use optional `String.prototype.split` param

---

examples/next-app/locales/client.ts
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/client/create-use-change-locale.ts
packages/next-international/src/app/client/index.ts

Relates to https://github.com/QuiiBz/next-international/issues/227

feat(next-international): only trigger suspense on first load

---

packages/next-international/src/app/middleware/index.ts

Add sameSite attribute to cookies to avoid warnings in Firefox.
Discussion: https://github.com/QuiiBz/next-international/issues/240

feat(next-international): set samesite attribute on cookies

---

packages/next-international/src/app/middleware/index.ts

Fixes #212 
The `response` from `NextResponse.next` and `NextResponse.redirect` doesn't contains any cookies except the `Next-Locale` set by the middleware.
At first, I wanted to clone the `headers` but this added a lot of elements that were not included in the basic Server Actions
EDIT: I've just noticed that the "Set-Cookie" header was defined for each request, which isn't great.

fix(next-international): preserve cookies in the middleware

---

docs/pages/docs/_meta.json
docs/pages/docs/rtl-support.mdx

Hello.
I've added a documentation page about RTL support, as we previously discussed here: https://github.com/QuiiBz/next-international/issues/220
I've documented two possible implementations.
However, the second, proposing an implementation based on a _useEffect_ call, seems to be a bad choice, after some rethinking.
I've written the documentation for it anyway in this PR, but I think we should remove it because of the point I mentioned in "Caveat".
> Note that this choice of implementation will cause an UI flickering when your user loads your web pages for the first time.  
> This is because the page will first be mounted with the default `dir` attribute value of your HTML node, then updates when the component including the `useEffect` is mounted. This will introduce CLS (Cumulative …

chore(docs): add rtl support

---

packages/next-international/src/app/middleware/index.ts

- Like the following PR https://github.com/QuiiBz/next-international/pull/238, when the URL are becoming long like https://github.com/QuiiBz/next-international/issues/..., there will be no loss of performance.
- I've also simplified the condition and added some comments on the `redirect` part but I'm not sure it's easy to read and understand this part so don't hesitate to give your opinion.
- In the `localeFromRequest` function, there were several assignments that weren't necessary, so I merged them.
- I removed the `clone()` call (from `nextUrl`) because it creates a new instance and it seems to be no longer documented on the doc, only on [error messages](https://nextjs.org/docs/messages/middleware-relative-urls)

perf(next-international): optimize middleware

---

examples/next-app/locales/client.ts
packages/next-international/src/app/client/create-i18n-provider-client.tsx
packages/next-international/src/app/client/create-use-change-locale.ts

Closes #290 
With this fix, I wasn't able to reproduce the crash.
It moves the call of `() => import("./en")` from `I18nProvider` to `I18nProviderWrapper`.
I changed this because according to the React documentation of `use` hook (https://react.dev/reference/react/use#streaming-data-from-server-to-client), the promise is executed and passed as a prop from the parent but awaited in the child.

fix: execute function in I18nProviderWrapper instead of I18nProvider

---

packages/next-international/src/app/client/create-use-change-locale.ts

So, currently, if we set the locale that is already set, it rerenders the page. To avoid this, I think an early locale check would be helpful.
Here is the record:
https://github.com/QuiiBz/next-international/assets/63459189/fa926b15-97dc-4ecb-b41e-9aac8f21cca5

feat: avoid refresh if new locale is already the current locale

---

packages/next-international/src/app/client/create-i18n-provider-client.tsx

fix: add missing import for "use"

---

packages/next-international/src/pages/create-i18n-provider.tsx

Closes https://github.com/QuiiBz/next-international/issues/344
The `fallbackLocale` prop from `I18nProvider` when using the Pages Router should accept nested locales.

fix(next-international): `fallbackLocale` type for pages router

---

examples/app/app/[locale]/client-component.tsx
examples/app/app/[locale]/layout.tsx
examples/app/app/[locale]/page.tsx
examples/app/locales/index.ts
packages/next-international/src/app/app/client.ts
packages/next-international/src/app/app/provider.tsx
packages/next-international/src/app/app/server.ts
packages/next-international/src/app/app/types.ts

The locale helper functions have been renamed to be more simple:
- `useCurrentLocale()` -> `useLocale()`
- `getCurrentLocale()` -> `useLocale()`
- No update: `useChangeLocale()`

feat(v2): `useLocale`, `useChangeLocale` support

---

docs/package.json
docs/pages/docs/app-setup.mdx
docs/pages/docs/app-static-rendering.md
docs/pages/docs/rtl-support.mdx
examples/next-app/app/[locale]/client/layout.tsx
examples/next-app/app/[locale]/page.tsx
examples/next-app/app/[locale]/subpage/page.tsx
examples/next-app/package.json
examples/next-pages/package.json
packages/next-international/package.json
packages/next-international/src/app/server/create-get-i18n.ts
packages/next-international/src/app/server/create-get-scoped-i18n.ts
packages/next-international/src/app/server/get-locale-cache.tsx
pnpm-lock.yaml

This PR updates `next-international` to support async changes in `next@15`.

feat: support `next@15`
