QuiiBz/next-international

- packages/next-international/package.json
- packages/next-international/src/i18n/create-use-i18n.ts
Remove useless `console.log` and bump to version `0.0.4`
> fix: remove console.log

- packages/next-international/README.md
- packages/next-international/package.json
- packages/next-international/src/i18n/create-define-locale.ts
- packages/next-international/src/i18n/create-i18n-provider.tsx
- packages/next-international/src/i18n/create-i18n.ts
- packages/next-international/src/i18n/create-use-change-locale.ts
- packages/next-international/src/i18n/create-use-i18n.ts
- packages/next-international/src/index.tsx
- packages/next-international/src/types.ts
Export `BaseLocale` and `LocaleValue`, see #7
> feat: explicitly type the locales

- packages/next-international/src/helpers/log.ts
- packages/next-international/src/i18n/create-get-locale-static-props.ts
- packages/next-international/src/i18n/create-i18n-provider.tsx
- packages/next-international/src/i18n/create-use-i18n.ts
Save some bytes by minifying parts of the code.
> feat: minify some code

- .gitignore
- package.json
- packages/next-international/__tests__/get-locale-static-props.test.ts
- packages/next-international/__tests__/i18n-provider.test.tsx
- packages/next-international/__tests__/use-i18n.test.tsx
- packages/next-international/src/index.tsx
- pnpm-lock.yaml
- vitest.config.ts
Add more tests and enable coverage.
> test: add I18nProvider tests

- examples/next/package.json
- packages/international-types/index.ts
- packages/international-types/package.json
- packages/next-international/package.json
- packages/next-international/src/i18n/create-use-i18n.ts
- pnpm-lock.yaml
Allow `boolean | null | undefined | Date` for `LocaleValue`
> feat(international-types): allow more values for locales

- examples/next/package.json
- packages/international-types/__tests/params.test.ts
- packages/international-types/index.ts
- packages/international-types/package.json
- packages/next-international/package.json
- pnpm-lock.yaml
> feat(international-types): improve plural params

- examples/next/package.json
- packages/international-types/__tests/params.test.ts
- packages/international-types/index.ts
- packages/international-types/package.json
- packages/next-international/package.json
- pnpm-lock.yaml
Fix multiple params in plural sentences.
> fix(international-types): multiple params in plural

- packages/international-types/__tests/params.test.ts
- packages/international-types/index.ts
- packages/international-types/package.json
Following https://github.com/QuiiBz/next-international/pull/45
> fix(international-types): allow multiple params in plural

- packages/international-types/package.json
- packages/next-international/package.json
- pnpm-lock.yaml
Closes https://github.com/QuiiBz/next-international/issues/53
> fix: remove workspace dependency

- packages/next-international/package.json
> fix(next-international): include types in files

- packages/next-international/tsconfig.json
- tsconfig.json
Fix the following tsc errors: https://github.com/QuiiBz/next-international/actions/runs/5498863195/jobs/10020640814
> fix(examples): tsc errors

- examples/next-app/locales/en.ts
- packages/next-international/src/app/client/index.ts
- packages/next-international/src/app/server/index.ts
> fix(next-international): support nested objects in App Router

- packages/next-international/README.md
- Add `'use client'` to snippets using Client Components
- Remove doc about `I18nProviderServer`
> chore: documentation fixes

- examples/next-app/app/[locale]/client/layout.tsx
- packages/next-international/src/app/client/create-i18n-provider-client.tsx
- packages/next-international/src/app/client/index.ts
- packages/next-international/src/common/flatten-locale.ts
- packages/next-international/src/pages/create-i18n-provider.tsx
Resolves https://github.com/QuiiBz/next-international/issues/67#issuecomment-1645165112
> fix(next-international): fallbackLocale type for nested objects locales

- packages/next-international/src/common/create-t.ts
Fix bug introduced in https://github.com/QuiiBz/next-international/pull/79
> fix(next-international): plural with scopes

- packages/international-types/README.md
> chore(international-types): update examples

- packages/next-international/README.md
Show an "Edit in CodeSandbox" button:
> chore: add codesandbox example

- packages/international-types/package.json
- packages/next-international/package.json
> feat: add `license` field to `package.json`

- docs/pages/docs/_meta.json
- docs/pages/docs/app-setup.mdx
- docs/pages/docs/app-static-rendering.mdx
- docs/pages/docs/pages-setup.mdx
- docs/pages/docs/pages-static-site-generation.md
Add Static Rendering (App Router) and Static Site Generation (Pages Router) documentation.
> docs: add static rendering section

- packages/next-international/src/app/middleware/index.ts
Regression of https://github.com/QuiiBz/next-international/pull/137/files
Relates to #143
> fix(next-international): infinite redirect with `rewrite` strategy

- packages/next-international/src/app/client/create-use-change-locale.ts
- packages/next-international/src/app/client/index.ts
> fix(next-international): `useChangeLocale` with pages starting with a locale

- packages/next-international/src/app/client/create-i18n-provider-client.tsx
- packages/next-international/src/types.ts
> fix(next-international): fallbackLocale with dot-notation TS error

- packages/next-international/src/app/middleware/index.ts
> fix(next-international): respect rewriteDefault strategy when changing locale

- .github/workflows/sherif.yml
- package.json
Add [Sherif](https://github.com/QuiiBz/sherif) to lint the monorepo.
> chore: add sherif to lint monorepo

- docs/package.json
- examples/next-app/package.json
- packages/next-international/src/app/middleware/index.ts
- pnpm-lock.yaml
> feat(next-international): redirect default with `rewriteDefault`

- packages/next-international/src/app/middleware/index.ts
> fix(next-international): rewrite strategies keep search params

- docs/pages/docs/rtl-support.mdx
- Add line highlights in the code examples
- Update some wording, with external references to MDN
- Fix the code examples highlighting bug
> chore(docs): improve RTL docs

- CONTRIBUTING.md
- docs/pages/index.mdx
- packages/next-international/README.md
> chore: add `CONTRIBUTING.md`

- packages/next-international/src/app/server/create-get-i18n.ts
- packages/next-international/src/app/server/create-get-scoped-i18n.ts
- packages/next-international/src/common/create-use-i18n.ts
- packages/next-international/src/common/create-use-scoped-i18n.ts
Closes https://github.com/QuiiBz/next-international/issues/302
Closes https://github.com/QuiiBz/next-international/issues/309
> perf(next-international): cache locales

- docs/package.json
- examples/next-app/package.json
- examples/next-pages/package.json
- packages/next-international/package.json
- packages/next-international/src/app/server/get-locale-cache.tsx
- pnpm-lock.yaml
> chore: update nextjs to 14

- docs/package.json
- docs/pages/_app.mdx
- pnpm-lock.yaml
Add `@vercel/speed-insights` to the docs: https://vercel.com/docs/speed-insights/quickstart
> feat(docs): add `@vercel/speed-insights`

- packages/next-international/src/app/server/create-get-scoped-i18n.ts
- packages/next-international/src/common/create-use-scoped-i18n.ts
Closes https://github.com/QuiiBz/next-international/issues/328
Closes #327
> fix(next-international): resolve consistent scoped types

- packages/next-international/src/app/client/create-i18n-provider-client.tsx
Closes https://github.com/QuiiBz/next-international/issues/330
Closes https://github.com/QuiiBz/next-international/issues/327
> fix(next-international): resolve `I18nProviderWrapper` interface

- packages/next-international/src/common/create-use-i18n.ts
- packages/next-international/src/common/create-use-scoped-i18n.ts
Closes https://github.com/QuiiBz/next-international/issues/346#issue-2121486391
Regression of https://github.com/QuiiBz/next-international/pull/314
> fix(next-international): locales switching on Pages Router

- docs/pages/docs/app-get-change-locale.md
- packages/next-international/package.json
- packages/next-international/src/app/server/create-get-current-locale.ts
> fix: update promise type
